[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  ADMIN_ACCESS_KEY = "Ciscolinuxadmin@22"
  ADMIN_SESSION_SECRET = "73086e5fe9a36758231dafa643640a5dd8593af720e4c2ca70ae8628bfa40cdf6e6ae4211454e4cb6d0823aa05fc37c6b0b7af7477ef8df8e30d83a621edc766"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_ZGVjZW50LW1vbmtmaXNoLTk3LmNsZXJrLmFjY291bnRzLmRldiQ"
  CLERK_SECRET_KEY = "sk_test_sbbCca36Um3M99lbVKyP5SxOFW3gRqV4Eu8CVppwNB"
  CLERK_WEBHOOK_SECRET = "whsec_jN/Fq5rYCiT2GUKDfdlTfl2SZxIpp0QZ"
  NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
  NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
  NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL = "/"
  NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL = "/"
  NEXT_PUBLIC_SUPABASE_URL = "https://hgxvlbpvxbliefqlxzak.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhneHZsYnB2eGJsaWVmcWx4emFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjUyMjQsImV4cCI6MjA3MTEwMTIyNH0.ensri-AI6SJRzW279b7j6gifpl3WhPSvU1of8jcXbGs"
  SUPABASE_URL = "https://hgxvlbpvxbliefqlxzak.supabase.co"
  SUPABASE_SERVICE_ROLE = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhneHZsYnB2eGJsaWVmcWx4emFrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTUyNTIyNCwiZXhwIjoyMDcxMTAxMjI0fQ.r7PTpDtAlRZGACUg4mOX3ryl_Orz8D3DrLJVj_UmwjA"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
